DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL
);

INSERT INTO urls VALUES (1, 'ru.hexlet.io', '2023-11-17 00:57:08.415069')